AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Morse Lambda Microservices Deployment

Parameters:
  ProjectName:
    Type: String
    Description: Connect Information name
  
    
Resources:
  
  